export const Products = [{
        url: "#",
        imageSrc: "#",
        altText: "some text",
        imgWidth: "50px",
        imgHeight: "50px",
        heading: "some heading",
        text: "some paragraph",
    },
    {
        url: "#",
        imageSrc: "#",
        altText: "some text",
        imgWidth: "50px",
        imgHeight: "50px",
        heading: "some heading",
        text: "some paragraph",
    },
    {
        url: "#",
        imageSrc: "#",
        altText: "some text",
        imgWidth: "50px",
        imgHeight: "50px",
        heading: "some heading",
        text: "some paragraph",
    },
    {
        url: "#",
        imageSrc: "#",
        altText: "some text",
        imgWidth: "50px",
        imgHeight: "50px",
        heading: "some heading",
        text: "some paragraph",
    },
];