export const Products = [{
        imageSrc: "reading-guide-ruler.png",
        altText: "An icon image of a book open as if being read.",
        imgWidth: "50px",
        imgHeight: "50px",
        heading: "Reading Guide Ruler",
        text: "While reading it can be difficult to focus on one line at a time when someone has ADHD or other learning issues such as dyslexia. It is possible to take command of reading with a reading guide ruler. These rulers have a large slot in the center that helps block out lines above and below that are often distracting. For a digital alternative web browsers can be set up using extensions like Reading Ruler which can make reading articles on the Web less distracting. The benefits to the user and company is that they reduce time spent on deciphering and processing material in the workplace. They create focus for the end user.",
    },
    {
        imageSrc: "headphones.png",
        altText: "An icon image of a pair of headphones.",
        imgWidth: "50px",
        imgHeight: "50px",
        heading: "Headphones",
        text: "Use of Noise Cancelling Headphones has been shown to aid in benefit people with Neuro Cognitive Disabilities. Companies making these available in the workplace and at the workstation helps to aid and improve performance and are shown to reduce stress on users with such needs. Earbuds can be a cheaper alternative.",
    },
    {
        imageSrc: "furniture.png",
        altText: "An icon image of a work station with a chair, desk and lamp.",
        imgWidth: "50px",
        imgHeight: "50px",
        heading: "Ergonomic Furniture",
        text: "Ergonomics is an area of science concerned with how the work performed affects the well-being of employees. It also looks for ways to ensure that the working environment is best suited to employees' needs and that everyone, regardless of ability, can work safely. Ergonomics considers an employee's physical capabilities, as well as any problems they may have, such as chronic pain or back problems, as well as external environmental elements like workplace furniture. Equipment size and controls, training methodologies, and the physical space in which employees operate are all environmental elements to consider when discussing staff welfare.",
    },
    {
        imageSrc: "ramp.png",
        altText: "An icon image depicting a ramp.",
        imgWidth: "50px",
        imgHeight: "50px",
        heading: "Ramps",
        text: "Install ramps where stairs and steps exist.",
    },
    {
        imageSrc: "digitalbrowser.png",
        altText: "An icon image depicting a computer screen with a software icon on it.",
        imgWidth: "50px",
        imgHeight: "50px",
        heading: "Digital Workstation",
        text: "Setting up computers with additional supports such as text to voice readers, and zoom features will benefit those with visual and hearing disabilities.",
    },
    {
        imageSrc: "employeehandbook.png",
        altText: "An icon image depicting a book with the title 'Employee Accessibility Handbook'.",
        imgWidth: "50px",
        imgHeight: "50px",
        heading: "Access Handbook",
        text: "An access handbook is an internal document that should be familiarized by all employees, including management, maintenance, and new hires. Its objective is to provide a simple manner of describing and explaining the features and facilities of a structure that must be maintained and/or enhanced in order to ensure that everyone has access to it.",
    },
    {
        imageSrc: "braille.png",
        altText: "An icon image depicting a sign with the braille format beneath.",
        imgWidth: "50px",
        imgHeight: "50px",
        heading: "Braille Stickers / Plates",
        text: "Use braille stickers on buttons, equipment and product labels to identify their purpose. This will aid blind users and those with visibility issues. These are stickers with raised indentations. They can be custom made with metal or using embossed techniques. Use in spaces like the kitchen area as well as this is often and area overlooked.",
    },
];