export const Products = [{
        imageSrc: "../static/images/reading-guide-ruler.png",
        altText: "An icon image of a book open as if being read.",
        imgWidth: "50px",
        imgHeight: "50px",
        heading: "Reading Guide Ruler",
        text: "While reading it can be difficult to focus on one line at a time when someone has ADHD or other learning issues such as dyslexia. It is possible to take command of reading with a reading guide ruler. These rulers have a large slot in the center that helps block out lines above and below that are often distracting. For a digital alternative web browsers can be set up using extensions like Reading Ruler which can make reading articles on the Web less distracting. The benefits to the user and company is that they reduce time spent on deciphering and processing material in the workplace. They create focus for the end user.",
    },
    {
        imageSrc: "headphones.png",
        altText: "An icon image of a pair of headphones.",
        imgWidth: "50px",
        imgHeight: "50px",
        heading: "Headphones",
        text: "Use of Noise Cancelling Headphones has been shown to aid in benefit people with Neuro Cognitive Disabilities. Companies making these available in the workplace and at the workstation helps to aid and improve performance and are shown to reduce stress on users with such needs. Earbuds can be a cheaper alternative.",
    },
    {
        imageSrc: "furniture.png",
        altText: "An icon image of a work station with a chair, desk and lamp.",
        imgWidth: "50px",
        imgHeight: "50px",
        heading: "Ergonomic Furniture",
        text: "Ergonomics is an area of science concerned with how the work performed affects the well-being of employees. It also looks for ways to ensure that the working environment is best suited to employees' needs and that everyone, regardless of ability, can work safely. Ergonomics considers an employee's physical capabilities, as well as any problems they may have, such as chronic pain or back problems, as well as external environmental elements like workplace furniture. Equipment size and controls, training methodologies, and the physical space in which employees operate are all environmental elements to consider when discussing staff welfare.",
    },
    {
        imageSrc: "ramp.png",
        altText: "An icon image depicting a ramp.",
        imgWidth: "50px",
        imgHeight: "50px",
        heading: "Ramps",
        text: "Install ramps where stairs and steps exist.",
    },
    {
        imageSrc: "ramp.png",
        altText: "An icon image depicting a ramp.",
        imgWidth: "50px",
        imgHeight: "50px",
        heading: "Ramps",
        text: "Install ramps where stairs and steps exist.",
    },
];